all-contributors/all-contributors.github.io

TIPS.md

Thought it would be useful for some who don't worry about size of the avatar and need a quicker solution

add ${username}.png tip

---

.all-contributorsrc
README.md

cc @ben-eb, @Jameskmonger, @jfmengels, @chrissimpkins, @bogas04 
Would love to get your feedback on this!

Reformat table to be able to fit more people #13

---

README.md

add ✨ to make the title less boring.

---

README.md

This was originally created in #17 by @frigginglorious and the commit has been attributed to him.
Could someone else click the merge button?

fix odd wording

---

README.md

PR includes: 
- new all contributors # style badge on the README page
- badge links to Contributors list on README page

added all contributors badge to README

---

README.md

Adding 🚇  emoji for infrastructure

---

README.md

As inspired by @captainsafia [here](https://twitter.com/captainsafia/status/804089602810269705).
Definitely open to different emoji/category names.

feat(emoji): add three more categories

---

README.md
other/IMPLEMENTATIONS.md

ref #43 
Could I get a review of this from someone?

chore(implementations): add implementations

---

README.md

Corrected the grammar of a sentence in the README.md file.

Correct grammar in README.md

---

other/IMPLEMENTATIONS.md

We recently started using all-contributors. So we want to let everyone else that we are in and we love this project! ❤️️

docs: add Angular Medellin to implementations

---

other/IMPLEMENTATIONS.md

Adding React Medellin Meetup

---

README.md

Hello! I just found out about this project and it is truly amazing, and I am so grateful for all the thought put into this!
One thing that struck me (neither as particularly good or bad, but just "noticed") was that the emoji key is sorted somewhat arbitrarily. "Code" happens to be the first item.
I suspect it's just the order things were added, or some such, but it does seem like an odd little signal which seems counter to the spirit of the project :)
Would you be willing to accept a re-sort?

Sort emoji key alphanumerically

---

README.md

Resolves #60 
---
Let me know if there's anything else I need to update @kentcdodds :v:

Add Ideas & Planning contribution type

---

other/IMPLEMENTATIONS.md

:v:
This project is heavily utilizing the new Ideas & Planning type from #60 :)

Add resourceful-redux implementation

---

other/IMPLEMENTATIONS.md

This project has been renamed 🙂

docs: rename resourceful-redux to redux-resource

---

README.md

Added platform type

---

README.md

The project doesn't exist anymore :cry:

chore: remove codesponsor

---

.all-contributorsrc
README.md

This is a more formalised statement from what the takeway was for me from #72.
As I haven't actually implemented the specification in any of my repos yet, I'm more than happy to hear thoughts from anyone who has on whether these statements and suggestions ring true, or if there are any changes required.

docs: added notes for repo maintainers (#72)

---

README.md

Suggesting the addition of
```
+💼 | Business Development | | people who execute on the business end
```

add business development to the list

---

other/IMPLEMENTATIONS.md

Added [syt123450/giojs](https://github.com/syt123450/giojs) to the implementations docs.

doc: add giojs to IMPLEMENTATIONS.md

---

README.md

fixing url to documentation in Portuguese

---

CONTRIBUTING.md
README.md
TIPS.md
docs/pt-BR/CONTRIBUTING.md
docs/pt-BR/DICAS.md
docs/pt-BR/README.md
docs/pt-BR/other/CODE_OF_CONDUCT.md
docs/pt-BR/other/IMPLEMENTATIONS.md
other/CODE_OF_CONDUCT.md
other/IMPLEMENTATIONS.md

Fixa all link reference to portuguese.

Fix link to portuguese

---

README.md
docs/es-ES/CONTRIBUTING.md
docs/es-ES/README.md
docs/es-ES/TIPS.md
docs/es-ES/other/CODE_OF_CONDUCT.md
docs/es-ES/other/IMPLEMENTATIONS.md

The Spanish version was added for project documentation. I think it can be improved, but it's a good start (I'm a native Spanish speaker)

Added Spanish documetation of the project

---

README.md

For free Pull Reminders usage, with permission from @jakebolam. Appreciate the support!

docs: add pull reminders badge

---

README.md

- Add link to all-contributors github bot
- Remove atom (unmaintained package, that is quite out-of-date)

docs: add link to github bot, remove atom (unmaintained package)

---

README.md

This goes hand in hand with
[all-contributors-cli#142](https://github.com/all-contributors/all-contributors-cli/pull/142).

docs(readme): added the maintenance category

---

README.md

This is a bump, of what was implemented in #126. We use semantic version for the emoji for our translation tables see #135. Adding a new emoji/category should be a 'feature' release.

feat: added the maintenance category, a bump of #125

---

README.md
package.json
yarn.lock

I added `commitizen` with the angular adapter and the commitizen badge like in [AC-CLI#143](https://github.com/all-contributors/all-contributors-cli/pull/143).

chore: added commitizen

---

docs/overview.md

Changes to README wording introduced in #167, this PR updates the website to the same

docs: clearer wording on praising contributions, code or not for website duplicate of #167

---

docs/project/contribute.md

Added the how to's on: logging into Crowdin and translating strings.
Solves most of #159 alongside what #163 resolves.

docs(contribute): added more content for translations

---

README.md

Update README.md for fixed typo "ch-CN" to "zh-CN"

---

docs/project/contribute.md

Adds a section on commits including a guideline.

docs(contribute): added commit section

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
crowdin.yaml
website/languages.js

feat: add Bahasa Indonesia language to website

---

website/static/css/homepage.css
yarn.lock

This has been bugging me since it first got deployed. Fixed spacing in the nav.
Take a look to make sure it didn't break anything else.

docs: navbar spacing fix

---

CODE_OF_CONDUCT.md
README.md
crowdin.yaml
website/_redirects
website/languages.js
website/static/index.html

@peterhuerlimann has completed german!
https://github.com/all-contributors/all-contributors/issues/143#issuecomment-468964523
Lets add it to the website 🗺

feat: add german

---

docs/project/contribute.md

Fixed a typo in step 3 and revised step 5.
closes #159

docs(contribute): improved translation section

---

website/siteConfig.js

Fixes #158. Thanks to @s-pace for the tips.
See the docs here: https://docusaurus.io/docs/en/search#docsNav

docs: only show results for current language

---

README.md
docs/project/contribute.md

also makes it more accessible for screen readers.
[View the readme change](https://github.com/all-contributors/all-contributors/blob/d5668ad33af754650de63e8d72ac0d3048102d45/README.md)

docs: avoid wrapping in language reference table

---

docs/project/implementations.md

add https://github.com/olavoparno/jest-badges-readme

docs(implementation): add project to it

---

.all-contributorsrc
docs/project/implementations.md

**What**:
Adding a new implementor to the list
**Why**:
Not necessary, would just like my project included on the list
**How**:
By editing the markdown file via Visual Studio Code
**Checklist**:
- [ x] Documentation
- [x ] Ready to be merged 
- [x ] Added myself to contributors table. 

add Kamino to list of implementors

---

.gitignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
crowdin.yaml
website/_redirects
website/languages.js

They are ready for the site #143 ✨ 🚀

feat(Translations): add Russian and Japanese

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
website/languages.js

Changing form of Polish country name to proper one
**What**:
- Anchors to Polish sites
**Why**:
- Because it was wrong form 😄 
**How**: .
**Checklist**:

docs(Typo in the Polish language anchors):

---

website/core/Footer.js
website/static/css/docs.css

✅ Closes: #155
**What**:
- Improve language dropdown according to general docs styling
- Add proper responsive styles for language dropdown for better UX on mobile devices
- Add minimalistic styles for footer
- Add background for a search bar and make a magnifier icon more lighter
**Why**:
- Because of #155 
**Checklist**:
According to style search results, in my opinion, it's okay how it is right now.

style: 💄 improve footer/language dropdown/search bar/nav bar

---

docs/emoji-key.md

**What**:
update docs, correct word: examples => example
**Why**:
`Unknown contribution type examples ...`
**How**:
update docs: examples => example
**Checklist**:

docs: fix word error

---

docs/emoji-key.md

**What**:
Fixes missing words describing the `tool` emoji
**Why**:
The description could be seen as confusing and/or unclear without it
**How**:
Added the same initial wording as other descriptions
**Checklist**:

docs(emoji): add missing words for "tool"

---

docs/cli/installation.md

fixed typo in installation.md
**What**: fixed typo
**Why**: -
**How**: -
**Checklist**:

docs: fixed typo

---

docs/project/implementations.md

**What**:
Add https://github.com/OperationCode/front-end to list of implementations
**Why**:
It may not be necessary, but I saw a list of implementations in the docs, and figured we'd throw our hat into the ring.
**How**:
Editing one line of markdown.
**Checklist**:

Add Operation Code to list of implementations

---

docs/cli/usage.md

**What**:
Update of the documentation to reflect changes done to the cli https://github.com/all-contributors/all-contributors-cli/pull/210
**Why**:
the badge section is now using delimiter tags to enable more customization in the badgeTemplate
**How**:
**Checklist**:

docs: badge pattern search changed

---

docs/project/implementations.md

**What**:
Add [CodeFund](https://github.com/gitcoinco/code_fund_ads) to the list of projects that use `all-contributors`.
**Checklist**:

docs(implementations): add CodeFund

---

docs/project/implementations.md

**What**: added Heimdal repo to "Who's using it"
**Why**: N/A
**How**: N/A
**Checklist**:
@all-contributors please add @cesar-richard to doc and userTesting

docs(implementations): add Heimdal project

---

docs/project/implementations.md

**Checklist**:
- [ x ] Documentation
- [ x ] Ready to be merged <!-- In your opinion, is this ready to be merged as soon as it's reviewed?

docs(implementations): add sytespace native

---

docs/emoji-key.md

**What**: Add `a11y` (Accessibility) contribution type.
**Why**: Discussed in all-contributors/all-contributors#320
**How**: Added a new contribution type in the emoji key
**Checklist**:

feat: add a11y contribution type

---

website/static/index.html

**What**:
**Why**:
**How**:
**Checklist**:

fix(index.html): fix spelling of GitHub

---

docs/emoji-key.md

Address #334 
**What**: Add "data" contributor category and relative emoji
**Why**: At the moment, there is no recognition for contribution of data (e.g. statistical matrices or lab measurements).
**How**: Simply added emoji in `docs/emoji-key.md`. Following #199 as a blueprint.
**Checklist**:

feat(emoji-key): added "Data" contributors

---

docs/cli/installation.md

**What**: Update the CLI installation documentation to mention the Arch Linux User Repository package for `all-contributors-cli`.
**Why**: This package makes it easier for Arch Linux users to install the CLI tool system-wide, especially for projects that are not node-based.
**Checklist**:

 docs(cli): mention the AUR package in installation.md 

---

docs/project/implementations.md

Awesome tool :)
**What**: Documentation
**Why**: New repository added.
**How**:  markdown changed.
**Checklist**:

docs(implementations): added ivanpaulovich/clean-architecture-manga

---

docs/project/implementations.md

Add a new Project that uses all-contributors

docs(implementations): adds tstrohmeier/docker-spark-development

---

docs/project/implementations.md

**What**:
Updating "Who's using it?" section
**Why**:
I started using the all-contributors bot to recognize contributors in my latest OS project.
**How**:

docs(implementations): update implementations.md

---

docs/emoji-key.md

✅ Closes: #423
**What**: 
* Adding emoji for mentoring 
* Minor style changes (consistent capitalisation at the beginning)
**Why**: Currently not covered by emoji key
**How**: Adding emoji with description to emoji key documentation
**Checklist**:

docs(emoji-key): adding emoji for mentoring

---

.all-contributorsrc

Please reffer to issue #426 for details

docs(all-contributorsrc): information update

---

README.md

Please reffer to issue #428 for details

docs(readme): updated as per #428

---

MAINTAINERS.md

**What**:
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
**Why**:
Misspellings are bad for project health.
**How**:
The misspellings have been reported at https://github.com/jsoref/all-contributors/commit/221eca7e4ed371efc0289395a3096a493202b8d4#commitcomment-46056327
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/all-contributors/commit/e2dda31e38e127d5dda8ba74655a645eb152489f
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.
**Checklist**:

docs(maintainers): fix spelling mistakes

---

docs/bot/overview.md
docs/bot/usage.md
docs/emoji-key.md
website/static/404.html
website/static/index.html

**What**:
Fix links
**Why**:
The app's repository was apparently renamed, and the comment parser moved within the app. That resulted in the links from the documentation not working....
**How**:
I guessed about the replacement paths (and used a script of mine to perform the replacements -- which should reduce my chance of making typos in correcting the paths).
**Checklist**:

docs(app): fix links for all-contributors/app

---

website/languages.js

**What**:
**Why**:
**How**:
**Checklist**:

refactor(website): update languages.js

---

website/static/404.html

**What**:
```
Github -> GitHub
```
**Why**:
consolidate the format,
**How**:
fixed comment.
**Checklist**:

chore(docs): fix GitHub format

---

docs/bot/usage.md

**What**: Added a more explicit note. @-mentioning when using the bot. Should Fix [all-contributors/app#354](https://github.com/all-contributors/app/issues/354)
**Why**: To be a little more explicit that bot will work best with @-mentions.
**How**: Added clarifying note below the note about natural language processing.
**Checklist**:
[x] Documentation
[x] Ready to be merged
[ ] Added myself to contributors table.

docs(bot): update usage.md to explicitly encourage @-mentions

---

README.md

**What**:
**Why**:
**How**:
**Checklist**:
- [x ] Ready to be merged 
- [x ] Added myself to contributors table. 
I think I may have added myself incorrectly

docs(README): fix specification link

---

.all-contributorsrc
README.md

**What**: Removing outdated badge and link to pullreminders
**Why**: 
* It has been shut down on 2022-06-21. That looks described in https://github.blog/changelog/2022-03-23-pull-panda-is-shutting-down/
* Awesome readme having missing badge 😢 
**How**:
**Checklist**:
https://github.blog/changelog/2022-03-23-pull-panda-is-shutting-down/

docs: remove badge to outdated pullreminders

---

docs/bot/installation.md

**What**: I added important steps for installation since I noticed it is missing and it is not easy to find the solutions.
**Why**: This will help others with their setup.
**How**: Update the installation section, added important steps
**Checklist**:

docs: add important steps for installation

---

crowdin.yaml

**What**:
Added unpublished languages that met the publication threshold
**Why**:
The content in those languages was translated enough to make the translations public.
**How**:
Added the [ISO 2 letter codes](https://www.sitepoint.com/iso-2-letter-language-codes/) for those languages
**Checklist**:

feat(translations): added Dutch, Romanian and Indonesian

---

docs/project/implementations.md

I've added respo ui to who's using it list.

docs(implementations): add `educatyeducate/respoui`

---

docs/project/contribute.md

**What**:
- Remove all Slack references since those are obsolete and irrelevant now.
**Why**: 
- Those references since are obsolete and irrelevant now.
**How**:
- Remove them all in the codebase.
**Checklist**:

chore: remove all Slack references

---

docs/project/implementations.md

**What**:
Added [Schrodinger-Hat/youtube-to-anchorfm](https://github.com/Schrodinger-Hat/youtube-to-anchorfm) to [Who's using it?](https://allcontributors.org/docs/en/project/implementations)
**Checklist**:

add Schrodinger-Hat/youtube-to-anchorfm

---

docs/bot/configuration.md

fix #637
**What**:
Updated link
**Why**:
To avoid 404
**How**:
Changed the link.
**Checklist**:

docs(bot): fix link in bot configuration page(#637)

---

docs/bot/usage.md

**What**:
- add usage for multiple contributors at once
- Prerequisite for https://github.com/all-contributors/app/pull/439
**Why**:
**How**:
**Checklist**:

docs: add usage for multiple contributors at once

---

docs/project/implementations.md

**What**:
**Why**:
**How**:
**Checklist**:

docs(implementations): add cleodora

---

docs/bot/configuration.md

**What**: 
Fixes #85 
Accomplished by adding support for wrapper configuration, linked to https://github.com/all-contributors/cli/pull/348
**Why**: In markdown implementations, styling isnt supported such that a minimalist version is limited. This wrapper configuration allows users to use different wrapping tags that can result in more minimalistic styles without css.
**How**: Providing configuration for custom wrapping tags instead of enforcing only `table` tags
**Checklist**:

Adding wrapperTemplate docs

---

crowdin.yaml

I've noticed a small but critical issue in the `crowdin.yaml` file, which has been present since last year. There is an unnecessary comma that is triggering the following error message during Netlify deployment: `Loading config failed. Please, check your configuration file.` This leads to the failure of the i18n feature, causing all translations to be unavailable on the docs.
To address this problem, I've removed the unnecessary comma, and the deployment issue [seems to be resolved](https://deploy-preview-726--allcontributors-org.netlify.app/docs/ko/overview). This change resolves #651, which was also referenced in issues #143 and #187.
-----
**Checklist**:

fix: 🐛 remove typo causing docs i18n deployment issue

---

docs/bot/installation.md

add an important information note for new repo installation w/ the bot. The config file should be created for the first time w/ mandatory values. The bot will add the default values afterwards.
**What**:
update all-contributors bot installation docs
**Why**:
When I installed the bot for the first time, I though that the `.all-contributorsrc` file would be created automatically by the bot. But it wasn't.
**How**:
Added a note (markdown citation) in the `installation.md` file of the bot docs.
**Checklist**:

docs(bot): :memo: update installation.md w/ notes

---

.github/workflows/build-website.yml
.github/workflows/lint.yml

closes #941
**What**:
We want to make sure that our documentation builds from the main branch
**Why**:
**How**:
**Checklist**:
🚀 🚀 🚀 🚀 🚀 🚀 🚀

chore: harden actions & run on main
